### ISSUE TITLE
autoplay

### ISSUE THREAD

**Issue by ghost** [juneyourtech/GM_YT#2]
for those who want the flash player to autoplay once is loaded, change the line 23,
   embedFrame.src = embedFrame.src + ("?showinfo=0");

by this

   embedFrame.src = embedFrame.src + ("?showinfo=0&autoplay=1");

works for me atleast

**Comment by juneyourtech** [comment]
@victordesfe I'm currently on the fence about autoplay. On one hand, it would reflect normal YouTube behaviour; on the other, some people actually prefer it, if autoplay were off. The third point is, that some people actually expect autoplay.

I just might include it, because there is no mechanism yet for automatic movement to the next track in a playlist.

**Comment by juneyourtech** [comment]
Switched autoplay on.

**Comment by mirh** [comment]
_Not_ working for me. 

EDIT: is this about continuous video playing, or just.. "open the page, video start"?

**Comment by juneyourtech** [comment]
@mirh Any new versions and improvements to the usercript are now in the [GM_YT_Flash](https://github.com/juneyourtech/GM_YT_Flash) repository, so as to separate design-related files from the one that forces Flash.

I'm not updating the userscript code in this repository, but at GM_YT_Flash.

Autoplay = Open page, video starts automatically. If it's turned off, the Flash-based player loads, but won't start playing the video.

**Comment by mirh** [comment]
Sorry I hadn't realized `GM_YT` and `GM_YT_Flash` were actually two different repo.
